name: CI/CD Sock Shop con Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COMPOSE_VERSION: 2.20.2

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout código
      uses: actions/checkout@v3

    # Paso 2: Instalar Docker Compose
    - name: Instalar Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v${{ env.COMPOSE_VERSION }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # Paso 3: Construir y levantar servicios con Docker Compose
    - name: Construir y levantar servicios con Docker Compose
      run: |
        cd deploy/docker
        docker-compose up -d --build

    # Paso 4: Ejecututar pruebas unitarias
    - name: Ejecututar pruebas unitarias
      run: echo "Aquí se ejecutarían pruebas con npm, pytest, etc."

    # Paso 5: Verificar servicios en ejecución
    - name: Verificar servicios en ejecución
      run: docker ps

    # Paso 6: Detener y eliminar contenedores (limpieza)
    - name: Detener y eliminar contenedores
      if: always()
      run: |
        cd deploy/docker
        docker-compose down